# This workflow will do a clean install of python dependancies and run Flake8
# For more information see: https://docs.github.com/en/actions/guides/building-and-testing-python

name: Lint

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8.5]

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependancies
        run: |
          pip install -r requirements.txt
      - name: Run Flake8
        run: |
          flake8 --config flake8 app/*
